# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-28 23:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_facility_metadata', '0005_auto_20181128_1810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datastore',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='datatype',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fileformat',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicaldatastore',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicaldatatype',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalfileformat',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalstoragetype',
            name='description',
            field=models.TextField(blank=True, help_text='This field represent the storage type to be used (e.g. S3 or PG)', null=True),
        ),
        migrations.AlterField(
            model_name='historicalvalue',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalvariable',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='storagetype',
            name='description',
            field=models.TextField(blank=True, help_text='This field represent the storage type to be used (e.g. S3 or PG)', null=True),
        ),
        migrations.AlterField(
            model_name='value',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='variable',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
