# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-23 19:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_facility_admin', '0002_auto_20180307_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalproject',
            name='request_id',
            field=models.IntegerField(blank=True, default=None, help_text=b'Id from the ticketing system, so it is possible to trace back if more info is needed.', null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='request_id',
            field=models.IntegerField(blank=True, default=None, help_text=b'Id from the ticketing system, so it is possible to trace back if more info is needed.', null=True),
        ),
    ]
