# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-23 20:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_facility_admin', '0003_auto_20180323_1553'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataagreement',
            name='internal_notes',
            field=models.TextField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='historicaldataagreement',
            name='internal_notes',
            field=models.TextField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='dataagreement',
            name='deletion_method',
            field=models.CharField(blank=True, choices=[(b'Delete', b'Delete'), (b'Shred', b'Shred')], default=b'Delete', max_length=256),
        ),
        migrations.AlterField(
            model_name='historicaldataagreement',
            name='deletion_method',
            field=models.CharField(blank=True, choices=[(b'Delete', b'Delete'), (b'Shred', b'Shred')], default=b'Delete', max_length=256),
        ),
    ]
