# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-30 14:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_facility_admin', '0004_auto_20180323_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalproject',
            name='type',
            field=models.CharField(choices=[(b'Capstone', b'Capstone'), (b'Class', b'Class'), (b'Class', b'Class'), (b'Data Transfer', b'Data Transfer')], default=b'Research', max_length=10),
        ),
        migrations.AlterField(
            model_name='project',
            name='type',
            field=models.CharField(choices=[(b'Capstone', b'Capstone'), (b'Class', b'Class'), (b'Class', b'Class'), (b'Data Transfer', b'Data Transfer')], default=b'Research', max_length=10),
        ),
    ]
