# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-30 19:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_facility_admin', '0005_auto_20180330_1016'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataset',
            name='status',
            field=models.CharField(choices=[(b'Active', b'Active'), (b'Disabled', b'Disabled')], default=b'Disabled', max_length=256),
        ),
        migrations.AddField(
            model_name='historicaldataset',
            name='status',
            field=models.CharField(choices=[(b'Active', b'Active'), (b'Disabled', b'Disabled')], default=b'Disabled', max_length=256),
        ),
    ]
