# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-03 23:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_facility_admin', '0006_auto_20180330_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalproject',
            name='status',
            field=models.CharField(choices=[(b'Pending Approval', b'Pending Approval'), (b'Active', b'Active'), (b'Archived', b'Archived')], default=b'Pending Approval', help_text=b"\n    <b>Pending Approval</b>: Represents projects that are not yet approved for usage.\n    These projects are ignored and will not be propagated to LDAP.\n    <br/><b>Active</b>: Active projects will have database schemas and project folders created.\n    <br/><b>Archived</b>: Archived projects don't have a database schema neither project folders.\n    ", max_length=20),
        ),
        migrations.AlterField(
            model_name='historicalproject',
            name='type',
            field=models.CharField(choices=[(b'Capstone', b'Capstone'), (b'Class', b'Class'), (b'Research', b'Research'), (b'Data Transfer', b'Data Transfer')], default=b'Research', max_length=10),
        ),
        migrations.AlterField(
            model_name='project',
            name='instructors',
            field=models.ForeignKey(blank=True, help_text=b'By default, instructors have Read/Write permissions \n    to the project folder and database schema. </br>\n    Any permissions granted on the project to an user that is also an instructor will be ignored.', null=True, on_delete=django.db.models.deletion.PROTECT, to='data_facility_admin.DfRole'),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[(b'Pending Approval', b'Pending Approval'), (b'Active', b'Active'), (b'Archived', b'Archived')], default=b'Pending Approval', help_text=b"\n    <b>Pending Approval</b>: Represents projects that are not yet approved for usage.\n    These projects are ignored and will not be propagated to LDAP.\n    <br/><b>Active</b>: Active projects will have database schemas and project folders created.\n    <br/><b>Archived</b>: Archived projects don't have a database schema neither project folders.\n    ", max_length=20),
        ),
        migrations.AlterField(
            model_name='project',
            name='type',
            field=models.CharField(choices=[(b'Capstone', b'Capstone'), (b'Class', b'Class'), (b'Research', b'Research'), (b'Data Transfer', b'Data Transfer')], default=b'Research', max_length=10),
        ),
    ]
