# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-10 18:28
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_facility_admin', '0007_auto_20180403_1914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaldataset',
            name='ldap_name',
            field=models.CharField(blank=True, db_index=True, error_messages={b'invalid': b'LDAP_NAME should contain at least 5 of the following: letters, numbers or "_" (underline).'}, help_text=b'Ldap_name should not have spaces or any special characters. It should have at least 5 characters consisting of: letters, numbers and "_" (underline). <br/> If left blank, it will be automatically generated.<br/><b>DO NOT CHANGE THIS VALUE AFTER THE OBJECT IS CREATED ON LDAP.</b>', max_length=256, null=True, validators=[django.core.validators.RegexValidator(regex=b'^[a-z0-9_-]{5,}$')]),
        ),
        migrations.AlterField(
            model_name='historicaldfrole',
            name='ldap_name',
            field=models.CharField(blank=True, db_index=True, error_messages={b'invalid': b'LDAP_NAME should contain at least 5 of the following: letters, numbers or "_" (underline).'}, help_text=b'Ldap_name should not have spaces or any special characters. It should have at least 5 characters consisting of: letters, numbers and "_" (underline). <br/> If left blank, it will be automatically generated.<br/><b>DO NOT CHANGE THIS VALUE AFTER THE OBJECT IS CREATED ON LDAP.</b>', max_length=256, null=True, validators=[django.core.validators.RegexValidator(regex=b'^[a-z0-9_-]{5,}$')]),
        ),
        migrations.AlterField(
            model_name='historicalproject',
            name='ldap_name',
            field=models.CharField(blank=True, db_index=True, error_messages={b'invalid': b'LDAP_NAME should contain at least 5 of the following: letters, numbers or "_" (underline).'}, help_text=b'Ldap_name should not have spaces or any special characters. It should have at least 5 characters consisting of: letters, numbers and "_" (underline). <br/> If left blank, it will be automatically generated.<br/><b>DO NOT CHANGE THIS VALUE AFTER THE OBJECT IS CREATED ON LDAP.</b>', max_length=256, null=True, validators=[django.core.validators.RegexValidator(regex=b'^[a-z0-9_-]{5,}$')]),
        ),
        migrations.AlterField(
            model_name='historicaluser',
            name='ldap_name',
            field=models.CharField(blank=True, db_index=True, error_messages={b'invalid': b'LDAP_NAME should contain at least 5 of the following: letters, numbers or "_" (underline).'}, help_text=b'Ldap_name should not have spaces or any special characters. It should have at least 5 characters consisting of: letters, numbers and "_" (underline). <br/> If left blank, it will be automatically generated.<br/><b>DO NOT CHANGE THIS VALUE AFTER THE OBJECT IS CREATED ON LDAP.</b>', max_length=256, null=True, validators=[django.core.validators.RegexValidator(regex=b'^[a-z0-9_-]{5,}$')]),
        ),
        migrations.AlterField(
            model_name='ldapobject',
            name='ldap_name',
            field=models.CharField(blank=True, error_messages={b'invalid': b'LDAP_NAME should contain at least 5 of the following: letters, numbers or "_" (underline).'}, help_text=b'Ldap_name should not have spaces or any special characters. It should have at least 5 characters consisting of: letters, numbers and "_" (underline). <br/> If left blank, it will be automatically generated.<br/><b>DO NOT CHANGE THIS VALUE AFTER THE OBJECT IS CREATED ON LDAP.</b>', max_length=256, null=True, unique=True, validators=[django.core.validators.RegexValidator(regex=b'^[a-z0-9_-]{5,}$')]),
        ),
    ]
