# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-13 23:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_facility_admin', '0009_auto_20181113_1856'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dataset',
            old_name='ingested_at',
            new_name='data_ingested_at',
        ),
        migrations.RenameField(
            model_name='historicaldataset',
            old_name='ingested_at',
            new_name='data_ingested_at',
        ),
        migrations.AddField(
            model_name='dataset',
            name='data_updated_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicaldataset',
            name='data_updated_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
