# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-16 01:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_facility_admin', '0010_auto_20181113_1859'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['first_name', 'last_name']},
        ),
        migrations.AlterField(
            model_name='project',
            name='owner',
            field=models.ForeignKey(blank=True, help_text=b'Enter Text to Search', null=True, on_delete=django.db.models.deletion.PROTECT, to='data_facility_admin.User'),
        ),
        migrations.AlterField(
            model_name='project',
            name='parent_project',
            field=models.ForeignKey(blank=True, help_text=b'Enter Text to Search', null=True, on_delete=django.db.models.deletion.PROTECT, to='data_facility_admin.Project'),
        ),
        migrations.AlterField(
            model_name='projectmember',
            name='member',
            field=models.ForeignKey(help_text=b'Enter Text to Search', on_delete=django.db.models.deletion.CASCADE, to='data_facility_admin.User'),
        ),
        migrations.AlterField(
            model_name='projectmember',
            name='project',
            field=models.ForeignKey(help_text=b'Enter Text to Search', on_delete=django.db.models.deletion.CASCADE, to='data_facility_admin.Project'),
        ),
    ]
