# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-16 01:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_facility_admin', '0011_auto_20181115_2022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasteward',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicaldatasteward',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
