# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-21 02:25
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_facility_admin', '0013_auto_20181120_0828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataset',
            name='source_url',
            field=models.URLField(blank=True, help_text=b'Indicates the URL for the Source Archive, when this information is needed.', max_length=256, null=True, validators=[django.core.validators.URLValidator]),
        ),
        migrations.AlterField(
            model_name='historicaldataset',
            name='source_url',
            field=models.URLField(blank=True, help_text=b'Indicates the URL for the Source Archive, when this information is needed.', max_length=256, null=True, validators=[django.core.validators.URLValidator]),
        ),
        migrations.AlterField(
            model_name='historicaltraining',
            name='url',
            field=models.URLField(blank=True, help_text=b'Training website, if any.', max_length=256, null=True, validators=[django.core.validators.URLValidator]),
        ),
        migrations.AlterField(
            model_name='historicaluser',
            name='email',
            field=models.EmailField(db_index=True, max_length=254, validators=[django.core.validators.EmailValidator]),
        ),
        migrations.AlterField(
            model_name='training',
            name='url',
            field=models.URLField(blank=True, help_text=b'Training website, if any.', max_length=256, null=True, validators=[django.core.validators.URLValidator]),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, validators=[django.core.validators.EmailValidator]),
        ),
    ]
