# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-28 22:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_facility_admin', '0014_auto_20181120_2125'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dataset',
            options={'ordering': ['dataset_id', 'name']},
        ),
        migrations.RenameField(
            model_name='dataset',
            old_name='doi',
            new_name='dataset_id',
        ),
        migrations.RenameField(
            model_name='historicaldataset',
            old_name='doi',
            new_name='dataset_id',
        ),
    ]
