# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-07 21:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_facility_admin', '0018_auto_20181128_1816'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaluser',
            name='contractors',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicaluser',
            name='foreign_national',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='contractors',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='foreign_national',
            field=models.BooleanField(default=False),
        ),
    ]
