# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-11 16:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_facility_admin', '0019_auto_20181207_1658'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicaluser',
            old_name='contractors',
            new_name='contractor',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='contractors',
            new_name='contractor',
        ),
    ]
