# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-12-13 20:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_facility_admin', '0020_auto_20181211_1124'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataset',
            name='require_ndas',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicaldataset',
            name='require_ndas',
            field=models.BooleanField(default=False),
        ),
    ]
