# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-24 13:48
from __future__ import unicode_literals

from django.db import migrations, models
from collections import namedtuple


class Migration(migrations.Migration):

    dependencies = [
        ('data_facility_admin', '0023_auto_20190123_1610'),
    ]

    # def create_default_classifications(apps, schema_editor):
    #     '''
    #     We can't import the Post model directly as it may be a newer
    #     version than this migration expects. We use the historical version.
    #     '''
    #     DataClassification = apps.get_model('data_facility_admin', 'DataClassification')
    #     # Classification = namedtuple(name, description, metadata_visibility, data_visibility)
    #     public = DataClassification.VISIBILITY_CHOICES.Public
    #     private = DataClassification.VISIBILITY_CHOICES.Private
    #
    #     classifications = [DataClassification(name='Green', metadata_visibility=public, data_visibility=public),
    #                        DataClassification(name='Restricted Green', metadata_visibility=public,
    #                                           data_visibility=private),
    #                        DataClassification(name='Yellow', metadata_visibility=public, data_visibility=private),
    #                        DataClassification(name='Red', metadata_visibility=private, data_visibility=private),
    #                        ]
    #
    #     classifications_dict = {}
    #     for classification in classifications:
    #         # Save classification
    #         classification.save()
    #         classifications_dict[classification.name] = classification
    #
    #     # Update datasets to point to correct classification


    operations = [
        migrations.CreateModel(
            name='DataClassification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('description', models.TextField(blank=True, null=True)),
                ('metadata_visibility', models.CharField(choices=[(b'Public', b'Public'), (b'Private', b'Private')], default=b'Public', help_text=b'<b>Public</b>: indicates that the metadata will be listed to everyone without requiring access. \n    </br><b>Private</b>: means that the metadata will not be listed unless the user has access to it.   \n    ', max_length=256)),
                ('data_visibility', models.CharField(choices=[(b'Public', b'Public'), (b'Private', b'Private')], default=b'Private', help_text=b'<b>Public</b>: indicates that the data will be listed to everyone without requiring access. \n    </br><b>Private</b>: means that the data will not be listed unless the user has access to it.   \n    ', max_length=256)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        # migrations.RunPython(create_default_classifications),
    ]
