# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-02-13 15:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_facility_admin', '0024_dataclassification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataclassification',
            name='metadata_visibility',
            field=models.CharField(choices=[(b'Public', b'Public'), (b'Private', b'Private')], default=b'Private', help_text=b'<b>Public</b>: indicates that the metadata will be listed to everyone without requiring access. \n    </br><b>Private</b>: means that the metadata will not be listed unless the user has access to it.   \n    ', max_length=256),
        ),
        migrations.AlterField(
            model_name='dataclassification',
            name='name',
            field=models.CharField(max_length=256, unique=True),
        ),
        migrations.AlterField(
            model_name='historicalprojecttool',
            name='tool_name',
            field=models.CharField(choices=[(b'Git Lab', b'Git Lab'), (b'Postgres', b'Postgres'), (b'Postgres RDS', b'Postgres RDS'), (b'Oracle', b'Oracle'), (b'POSIX', b'POSIX'), (b'Other', b'Other'), (b'Python', b'Python'), (b'R', b'R'), (b'Stata', b'Stata')], default=b'Python', max_length=10),
        ),
        migrations.AlterField(
            model_name='keyword',
            name='name',
            field=models.CharField(max_length=256, unique=True),
        ),
        migrations.AlterField(
            model_name='projecttool',
            name='tool_name',
            field=models.CharField(choices=[(b'Git Lab', b'Git Lab'), (b'Postgres', b'Postgres'), (b'Postgres RDS', b'Postgres RDS'), (b'Oracle', b'Oracle'), (b'POSIX', b'POSIX'), (b'Other', b'Other'), (b'Python', b'Python'), (b'R', b'R'), (b'Stata', b'Stata')], default=b'Python', max_length=10),
        ),
    ]
