# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-02-14 23:59
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_facility_admin', '0024_dataclassification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalprojecttool',
            name='request_id',
        ),
        migrations.RemoveField(
            model_name='historicalprojecttool',
            name='status',
        ),
        migrations.AddField(
            model_name='historicalprojecttool',
            name='notes',
            field=models.TextField(blank=True, help_text=b'Id for from the ticketing system (if not the same from project creation), so it is possible to trace back if more info is needed.', null=True),
        ),
        migrations.AddField(
            model_name='historicalprojecttool',
            name='system_info',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projecttool',
            name='notes',
            field=models.TextField(blank=True, help_text=b'Id for from the ticketing system (if not the same from project creation), so it is possible to trace back if more info is needed.', null=True),
        ),
        migrations.AddField(
            model_name='projecttool',
            name='system_info',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dataclassification',
            name='metadata_visibility',
            field=models.CharField(choices=[(b'Public', b'Public'), (b'Private', b'Private')], default=b'Private', help_text=b'<b>Public</b>: indicates that the metadata will be listed to everyone without requiring access. \n    </br><b>Private</b>: means that the metadata will not be listed unless the user has access to it.   \n    ', max_length=256),
        ),
        migrations.AlterField(
            model_name='dataclassification',
            name='name',
            field=models.CharField(max_length=256, unique=True),
        ),
        migrations.AlterField(
            model_name='historicalprojecttool',
            name='additional_info',
            field=models.CharField(blank=True, help_text=b'Additional info, such as database name. In case it does not follow the Data Facility convention.', max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='historicalprojecttool',
            name='tool_name',
            field=models.CharField(choices=[(b'SelectOne', b'SelectOne'), (b'GitLab', b'GitLab'), (b'Postgres', b'Postgres'), (b'PG_RDS', b'PG_RDS'), (b'Oracle', b'Oracle'), (b'POSIX', b'POSIX'), (b'Other', b'Other'), (b'Python', b'Python'), (b'R', b'R'), (b'Stata', b'Stata'), (b'Workspace_K8s', b'Workspace_K8s')], default=b'SelectOne', max_length=10),
        ),
        migrations.AlterField(
            model_name='keyword',
            name='name',
            field=models.CharField(max_length=256, unique=True),
        ),
        migrations.AlterField(
            model_name='projecttool',
            name='additional_info',
            field=models.CharField(blank=True, help_text=b'Additional info, such as database name. In case it does not follow the Data Facility convention.', max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='projecttool',
            name='tool_name',
            field=models.CharField(choices=[(b'SelectOne', b'SelectOne'), (b'GitLab', b'GitLab'), (b'Postgres', b'Postgres'), (b'PG_RDS', b'PG_RDS'), (b'Oracle', b'Oracle'), (b'POSIX', b'POSIX'), (b'Other', b'Other'), (b'Python', b'Python'), (b'R', b'R'), (b'Stata', b'Stata'), (b'Workspace_K8s', b'Workspace_K8s')], default=b'SelectOne', max_length=10),
        ),
        migrations.RemoveField(
            model_name='projecttool',
            name='request_id',
        ),
        migrations.RemoveField(
            model_name='projecttool',
            name='status',
        ),
        migrations.AlterUniqueTogether(
            name='projecttool',
            unique_together=set([('project', 'tool_name')]),
        ),
    ]
