# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-02-22 16:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_facility_admin', '0025_auto_20190214_1859'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['first_name', 'last_name', 'ldap_name', 'email']},
        ),
        migrations.AlterField(
            model_name='historicalprojecttool',
            name='tool_name',
            field=models.CharField(choices=[(b'SelectOne', b'SelectOne'), (b'GitLab', b'GitLab'), (b'Postgres', b'Postgres'), (b'PG_RDS', b'PG_RDS'), (b'Oracle', b'Oracle'), (b'POSIX', b'POSIX'), (b'Other', b'Other'), (b'Python', b'Python'), (b'R', b'R'), (b'Stata', b'Stata'), (b'Workspace_K8s', b'Workspace_K8s')], default=b'SelectOne', max_length=100),
        ),
        migrations.AlterField(
            model_name='projecttool',
            name='tool_name',
            field=models.CharField(choices=[(b'SelectOne', b'SelectOne'), (b'GitLab', b'GitLab'), (b'Postgres', b'Postgres'), (b'PG_RDS', b'PG_RDS'), (b'Oracle', b'Oracle'), (b'POSIX', b'POSIX'), (b'Other', b'Other'), (b'Python', b'Python'), (b'R', b'R'), (b'Stata', b'Stata'), (b'Workspace_K8s', b'Workspace_K8s')], default=b'SelectOne', max_length=100),
        ),
    ]
