# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-02-22 23:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_facility_admin', '0026_auto_20190222_1145'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalproject',
            old_name='expected_outcomes',
            new_name='outcomes',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='expected_outcomes',
            new_name='outcomes',
        ),
        migrations.AddField(
            model_name='historicalproject',
            name='mission',
            field=models.TextField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='historicalproject',
            name='question',
            field=models.TextField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='historicalproject',
            name='requester',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='data_facility_admin.User'),
        ),
        migrations.AddField(
            model_name='project',
            name='mission',
            field=models.TextField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='project',
            name='question',
            field=models.TextField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='project',
            name='requester',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requester', to='data_facility_admin.User'),
        ),
        migrations.AlterField(
            model_name='project',
            name='owner',
            field=models.ForeignKey(blank=True, help_text=b'Enter Text to Search', null=True, on_delete=django.db.models.deletion.CASCADE, to='data_facility_admin.User'),
        ),
    ]
