# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-03 18:58
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_facility_admin', '0027_auto_20190222_1835'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataset',
            name='gmeta',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicaldataset',
            name='gmeta',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
