# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-02-14 20:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_facility_admin', '0027_auto_20190214_1504'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalprojecttool',
            name='system_info',
            field=models.TextField(blank=True, max_length=1024),
        ),
        migrations.AddField(
            model_name='projecttool',
            name='system_info',
            field=models.TextField(blank=True, max_length=1024),
        ),
    ]
