# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-02-14 20:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_facility_admin', '0028_auto_20190214_1528'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalprojecttool',
            name='status',
        ),
        migrations.RemoveField(
            model_name='projecttool',
            name='status',
        ),
    ]
