# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-03 19:11
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_facility_admin', '0028_auto_20190303_1358'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dataset',
            old_name='gmeta',
            new_name='detailed_gmeta',
        ),
        migrations.RenameField(
            model_name='historicaldataset',
            old_name='gmeta',
            new_name='detailed_gmeta',
        ),
        migrations.AddField(
            model_name='dataset',
            name='search_gmeta',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicaldataset',
            name='search_gmeta',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
