# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-02-14 20:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_facility_admin', '0029_auto_20190214_1535'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='projecttool',
            unique_together=set([('project', 'tool_name')]),
        ),
    ]
