# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-02-14 20:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_facility_admin', '0030_auto_20190214_1541'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalprojecttool',
            name='request_id',
        ),
        migrations.RemoveField(
            model_name='projecttool',
            name='request_id',
        ),
        migrations.AddField(
            model_name='historicalprojecttool',
            name='notes',
            field=models.TextField(blank=True, help_text=b'Id for from the ticketing system (if not the same from project creation), so it is possible to trace back if more info is needed.', null=True),
        ),
        migrations.AddField(
            model_name='projecttool',
            name='notes',
            field=models.TextField(blank=True, help_text=b'Id for from the ticketing system (if not the same from project creation), so it is possible to trace back if more info is needed.', null=True),
        ),
        migrations.AlterField(
            model_name='historicalprojecttool',
            name='additional_info',
            field=models.CharField(blank=True, default=b'None', help_text=b'Additional info, such as database name. In case it does not follow the Data Facility convention.', max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='historicalprojecttool',
            name='system_info',
            field=models.TextField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='projecttool',
            name='additional_info',
            field=models.CharField(blank=True, default=b'None', help_text=b'Additional info, such as database name. In case it does not follow the Data Facility convention.', max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='projecttool',
            name='system_info',
            field=models.TextField(blank=True, max_length=1024, null=True),
        ),
    ]
