# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-02-14 21:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_facility_admin', '0031_auto_20190214_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalprojecttool',
            name='tool_name',
            field=models.CharField(choices=[(b'SelectOne', b'SelectOne'), (b'GitLab', b'GitLab'), (b'Postgres', b'Postgres'), (b'PG_RDS', b'PG_RDS'), (b'Oracle', b'Oracle'), (b'POSIX', b'POSIX'), (b'Other', b'Other'), (b'Python', b'Python'), (b'R', b'R'), (b'Stata', b'Stata')], default=b'SelectOne', max_length=10),
        ),
        migrations.AlterField(
            model_name='projecttool',
            name='tool_name',
            field=models.CharField(choices=[(b'SelectOne', b'SelectOne'), (b'GitLab', b'GitLab'), (b'Postgres', b'Postgres'), (b'PG_RDS', b'PG_RDS'), (b'Oracle', b'Oracle'), (b'POSIX', b'POSIX'), (b'Other', b'Other'), (b'Python', b'Python'), (b'R', b'R'), (b'Stata', b'Stata')], default=b'SelectOne', max_length=10),
        ),
    ]
