# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-09 19:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_facility_admin', '0031_auto_20190306_1631'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dataset',
            name='shareable',
        ),
        migrations.RemoveField(
            model_name='historicaldataset',
            name='shareable',
        ),
        migrations.AddField(
            model_name='dataset',
            name='available',
            field=models.BooleanField(default=True, help_text=b'Indicates if this dataset available to be listed for usage.'),
        ),
        migrations.AddField(
            model_name='historicaldataset',
            name='available',
            field=models.BooleanField(default=True, help_text=b'Indicates if this dataset available to be listed for usage.'),
        ),
    ]
