# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-02-14 21:25
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_facility_admin', '0032_auto_20190214_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalprojecttool',
            name='additional_info',
            field=models.CharField(blank=True, help_text=b'Additional info, such as database name. In case it does not follow the Data Facility convention.', max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='historicalprojecttool',
            name='system_info',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='projecttool',
            name='additional_info',
            field=models.CharField(blank=True, help_text=b'Additional info, such as database name. In case it does not follow the Data Facility convention.', max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='projecttool',
            name='system_info',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
