# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-15 13:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_facility_admin', '0034_auto_20190424_0717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalproject',
            name='status',
            field=models.CharField(choices=[(b'Pending Approval', b'Pending Approval'), (b'Active', b'Active'), (b'Archived', b'Archived')], default=b'Pending Approval', help_text=b"\n    <b>Pending Approval</b>: Represents projects that are not yet approved for usage.\n    These projects are ignored and will not be propagated to LDAP.\n    <br/><b>Active</b>: Active projects will have database schemas and project folders created.\n    <br/><b>Archived</b>: Archived projects don't have a database schema neither project folders.\n    ", max_length=256),
        ),
        migrations.AlterField(
            model_name='historicalproject',
            name='type',
            field=models.CharField(choices=[(b'Capstone', b'Capstone'), (b'Class', b'Class'), (b'Research', b'Research'), (b'Data Transfer', b'Data Transfer')], default=b'Research', max_length=256),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[(b'Pending Approval', b'Pending Approval'), (b'Active', b'Active'), (b'Archived', b'Archived')], default=b'Pending Approval', help_text=b"\n    <b>Pending Approval</b>: Represents projects that are not yet approved for usage.\n    These projects are ignored and will not be propagated to LDAP.\n    <br/><b>Active</b>: Active projects will have database schemas and project folders created.\n    <br/><b>Archived</b>: Archived projects don't have a database schema neither project folders.\n    ", max_length=256),
        ),
        migrations.AlterField(
            model_name='project',
            name='type',
            field=models.CharField(choices=[(b'Capstone', b'Capstone'), (b'Class', b'Class'), (b'Research', b'Research'), (b'Data Transfer', b'Data Transfer')], default=b'Research', max_length=256),
        ),
    ]
