# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-06-19 21:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_facility_admin', '0035_auto_20190515_0920'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalproject',
            name='end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalproject',
            name='start',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='start',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
