# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-08-05 18:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_facility_admin', '0036_auto_20190619_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='databaseschema',
            name='name',
            field=models.CharField(max_length=256, unique=True),
        ),
        migrations.AlterField(
            model_name='historicaldatabaseschema',
            name='name',
            field=models.CharField(db_index=True, max_length=256),
        ),
    ]
