# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-08-27 19:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_facility_admin', '0039_auto_20190807_1304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalproject',
            name='end',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='historicalproject',
            name='start',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='historicalprojectmember',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='end',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='start',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='projectmember',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
